apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-gowiki.fullname" . }}
  labels:
    {{- include "simple-gowiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.containerPort }}
    protocol: TCP
  selector:
    {{- include "simple-gowiki.selectorLabels" . | nindent 4 }}
